spring:
  banner:
    location: classpath:/banner.txt
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: false
#        generate_statistics: false
#        jdbc:
#          batch_size: 1000
  flyway:
    locations: classpath:db/migration/{vendor}
    out-of-order: true

logging:
  file:
    name: ./logs/yaci-indexer.log


