create table address_utxo
(
    output_index          integer      not null,
    tx_hash               varchar(255) not null,
    amounts               jsonb,
    block                 bigint,
    block_hash            varchar(255),
    data_hash             varchar(255),
    inline_datum          oid,
    owner_addr            varchar(255),
    owner_stake_addr      varchar(255),
    reference_script_hash oid,
    spent                 boolean,
    spent_at_slot         boolean,
    primary key (output_index, tx_hash)
);

create table block
(
    block_hash       varchar(255) not null
        primary key,
    block            bigint,
    block_body_hash  varchar(255),
    block_body_size  bigint,
    epoch            bigint,
    era              integer,
    issuer_vkey      varchar(255),
    leader_vrf       jsonb,
    nonce_vrf        jsonb,
    prev_hash        varchar(255),
    protocol_version varchar(255),
    slot             bigint,
    vrf_result       jsonb,
    vrf_vkey         varchar(255)
);


create table error
(
    id         integer generated by default as identity
        primary key,
    block      bigint,
    block_hash varchar(255),
    error_code varchar(255),
    reason     oid,
    tx_hash    varchar(255)
);


create table invalid_transaction
(
    tx_hash     varchar(255) not null
        primary key,
    transaction jsonb
);


create table rollback
(
    block_hash varchar(255) not null
        primary key,
    block      bigint,
    epoch      bigint
);

create table transaction
(
    tx_hash                 varchar(255) not null
        primary key,
    auxiliary_datahash      varchar(255),
    block                   bigint,
    collateral_inputs       jsonb,
    collateral_return       jsonb,
    fee                     numeric(19, 2),
    inputs                  jsonb,
    invalid                 boolean,
    network_id              integer,
    outputs                 jsonb,
    reference_inputs        jsonb,
    required_signers        jsonb,
    script_datahash         varchar(255),
    slot                    bigint,
    total_collateral        numeric(19, 2),
    ttl                     bigint,
    validity_interval_start bigint
);

