package com.bloxbean.cardano.yaci.store.analytics.query.model;

import java.util.List;
import java.util.Map;

/**
 * Static metadata for an analytics table, enriched beyond what DESCRIBE provides.
 * Helps AI agents build correct and efficient DuckDB queries.
 */
public record TableMetadata(
        String name,
        String description,
        String partitionStrategy,
        String partitionColumn,
        List<String> queryHints
) {

    private static final Map<String, TableMetadata> METADATA = Map.ofEntries(
            entry("transaction",
                    "All Cardano transactions with fees, validity, epoch, slot, block reference",
                    "DAILY", "date",
                    List.of("Filter on 'epoch' or 'date' for partition pruning",
                            "Column 'invalid' is boolean (true = failed phase-2 validation)",
                            "Column 'fee' is in lovelace (1 ADA = 1,000,000 lovelace)",
                            "Columns 'inputs' and 'outputs' are JSON strings — prefer joining address_utxo/tx_input instead")),
            entry("block",
                    "All blocks with producer (slot_leader), body size, tx count, total fees, era",
                    "DAILY", "date",
                    List.of("Filter on 'epoch' or 'date' for partition pruning",
                            "Column 'slot_leader' is the pool ID (hex) that produced the block",
                            "Column 'no_of_txs' is the transaction count per block")),
            entry("address",
                    "Optional unique-address index with payment/stake credentials and the slot where first seen; " +
                            "source data is populated when store.utxo.save-address=true",
                    "DAILY", "date",
                    List.of("OPTIONAL: absence means unavailable; a row count of zero means currently empty, not necessarily disabled",
                            "Filter on 'date' or 'slot' for partition pruning",
                            "Fallback: use address_utxo to find addresses that own outputs; it is not a complete list of every address ever seen")),
            entry("address_balance",
                    "Optional address balance update history by asset unit; source data is populated when " +
                            "store.account.balance-aggregation-enabled=true and store.account.address-balance-enabled=true",
                    "DAILY", "date",
                    List.of("OPTIONAL: absence means unavailable; a row count of zero means currently empty, not necessarily disabled",
                            "Each daily partition contains the latest update within that day, not a complete end-of-day snapshot of every address",
                            "Fallback for current balances: use GET /addresses/{address}/amounts or, when MCP is enabled, 'analytics-address-balance'",
                            "Amounts are raw asset quantities; lovelace is 1 ADA = 1,000,000 lovelace")),
            entry("address_tx_amount",
                    "Optional per-transaction asset amount changes grouped by address; source data is populated " +
                            "when store.account.save-address-tx-amount=true",
                    "DAILY", "date",
                    List.of("OPTIONAL: absence means unavailable; a row count of zero means currently empty, not necessarily disabled",
                            "Filter on 'date' or 'slot' for partition pruning",
                            "Fallback: derive UTXO flows from address_utxo, tx_input, and transaction; this is not a one-to-one replacement")),
            entry("address_utxo",
                    "Flattened UTXO outputs — one row per asset per output (NO JSONB). " +
                            "1 UTXO with 3 assets = 3 rows with direct asset_unit, policy_id, asset_name, quantity columns",
                    "DAILY", "date",
                    List.of("FLATTENED: each asset in a UTXO is a separate row — no JSONB parsing needed",
                            "For ADA balance: WHERE asset_unit = 'lovelace'",
                            "For native token: WHERE asset_unit = '<policyId><assetNameHex>'",
                            "BALANCE QUERIES: For a current single-address balance use GET /addresses/{address}/amounts; " +
                                    "when MCP is enabled, use 'analytics-address-balance'. For top N addresses with MCP, " +
                                    "use 'analytics-top-balances' (exported data).",
                            "ALWAYS filter on 'date' or 'epoch' — table is 37GB / 1.47B rows",
                            "Column 'quantity' is DECIMAL(38,0) — lovelace for ADA, raw amount for tokens")),
            entry("tx_input",
                    "Spent output log — records when each UTXO was consumed. Partitioned by SPENT date (not creation date)",
                    "DAILY", "date",
                    List.of("Partitioned by SPENT date (when the output was consumed), not creation date",
                            "Join with address_utxo: ON ti.tx_hash = u.tx_hash AND ti.output_index = u.output_index",
                            "Column 'spent_tx_hash' is the transaction that consumed this output",
                            "BALANCE QUERIES: For a current single-address balance use GET /addresses/{address}/amounts; " +
                                    "when MCP is enabled, use 'analytics-address-balance'.")),
            entry("epoch_stake",
                    "Stake delegation snapshots per epoch — amount delegated to each pool by each address",
                    "EPOCH", "epoch",
                    List.of("Partitioned by epoch — filter on 'epoch' for fast queries",
                            "Column 'pool_id' is the pool hash (hex)",
                            "Column 'amount' is delegated stake in lovelace")),
            entry("epoch",
                    "Optional epoch summaries including block count, transaction count, output, fee, and timing totals; " +
                            "source data is populated when store.epoch.enabled=true",
                    "EPOCH", "epoch",
                    List.of("OPTIONAL: absence means unavailable; a row count of zero means currently empty, not necessarily disabled",
                            "Partitioned by epoch",
                            "Fallback: aggregate block and transaction by epoch for counts and fees; not every summary field has an exact fallback")),
            entry("reward",
                    "Reward distribution per epoch — staking rewards paid to delegators",
                    "EPOCH", "epoch",
                    List.of("Partitioned by epoch",
                            "Column 'type' values: 'member' (delegator), 'leader' (pool operator), 'treasury', 'reserves'",
                            "Column 'amount' is in lovelace",
                            "Column 'pool_id' is the pool that generated the reward")),
            entry("delegation",
                    "Delegation certificates — when addresses delegate to pools",
                    "DAILY", "date",
                    List.of("Column 'pool_id' is the target pool",
                            "Column 'address' is the stake address")),
            entry("pool",
                    "Stake pool lifecycle events (registrations, retirements)",
                    "DAILY", "date",
                    List.of("Column 'status' indicates registration or retirement",
                            "Column 'pool_id' is the pool hash")),
            entry("pool_registration",
                    "Pool registration certificates with metadata",
                    "DAILY", "date",
                    List.of("Contains pool parameters: pledge, cost, margin, metadata URL")),
            entry("pool_retirement",
                    "Pool retirement certificates",
                    "DAILY", "date",
                    List.of("Column 'retire_epoch' is the epoch when retirement takes effect")),
            entry("voting_procedure",
                    "Governance votes (Conway era) — DRep, SPO, and Committee votes on proposals",
                    "DAILY", "date",
                    List.of("Column 'voter_type' values: 'DREP_KEY_HASH', 'STAKING_POOL_KEY_HASH', 'CONSTITUTIONAL_COMMITTEE_HOT_KEY_HASH'",
                            "Column 'vote' values: 'YES', 'NO', 'ABSTAIN'",
                            "Columns 'gov_action_tx_hash' + 'gov_action_index' reference the proposal")),
            entry("gov_action_proposal",
                    "Governance proposals submitted on-chain",
                    "DAILY", "date",
                    List.of("Column 'type' values: 'PARAMETER_CHANGE', 'HARD_FORK_INITIATION', 'TREASURY_WITHDRAWALS', 'NO_CONFIDENCE', etc.",
                            "Column 'details' is a JSON string with proposal-specific parameters")),
            entry("gov_action_proposal_status",
                    "Governance proposal status changes (enacted, expired, etc.)",
                    "EPOCH", "epoch",
                    List.of()),
            entry("drep",
                    "DRep (Delegated Representative) registrations and status",
                    "DAILY", "date",
                    List.of("Conway era only (2024+)",
                            "Column 'drep_id' is the bech32 DRep identifier")),
            entry("drep_registration",
                    "DRep registration and deregistration certificates",
                    "DAILY", "date",
                    List.of()),
            entry("drep_dist",
                    "DRep voting power distribution per epoch",
                    "EPOCH", "epoch",
                    List.of("Partitioned by epoch",
                            "Column 'amount' is the voting power in lovelace")),
            entry("delegation_vote",
                    "Vote delegation certificates — delegating voting power to a DRep",
                    "DAILY", "date",
                    List.of()),
            entry("committee_member",
                    "Constitutional Committee members",
                    "EPOCH", "epoch",
                    List.of()),
            entry("committee_state",
                    "Constitutional Committee state changes",
                    "EPOCH", "epoch",
                    List.of()),
            entry("committee",
                    "Constitutional Committee configuration",
                    "EPOCH", "epoch",
                    List.of()),
            entry("committee_registration",
                    "Committee member hot key registrations",
                    "DAILY", "date",
                    List.of()),
            entry("committee_deregistration",
                    "Committee member hot key deregistrations",
                    "DAILY", "date",
                    List.of()),
            entry("constitution",
                    "On-chain constitution documents",
                    "EPOCH", "epoch",
                    List.of()),
            entry("assets",
                    "Token mint and burn events",
                    "DAILY", "date",
                    List.of("Column 'mint_type' values: 'MINT' or 'BURN'",
                            "Column 'unit' = policyId + assetName (hex)",
                            "Column 'fingerprint' is the CIP-14 asset fingerprint")),
            entry("transaction_metadata",
                    "Transaction metadata (auxiliary data) with label-based indexing",
                    "DAILY", "date",
                    List.of("Column 'label' is the metadata label number (e.g., 721 for NFT metadata)",
                            "Column 'body' contains the metadata content")),
            entry("transaction_scripts",
                    "Script executions in transactions (Plutus, native scripts)",
                    "DAILY", "date",
                    List.of("Contains script hashes, execution units (mem/steps), redeemers")),
            entry("transaction_witness",
                    "Optional transaction witnesses including public keys, signatures, and witness type; source data " +
                            "is populated when store.transaction.save-witness=true",
                    "DAILY", "date",
                    List.of("OPTIONAL: absence means unavailable; a row count of zero means currently empty, not necessarily disabled",
                            "Join to transaction using 'tx_hash'",
                            "No equivalent fallback: transaction does not contain witness public keys or signatures")),
            entry("script",
                    "Script definitions (Plutus V1/V2/V3, native scripts)",
                    "DAILY", "date",
                    List.of()),
            entry("datum",
                    "Plutus datums stored on-chain",
                    "DAILY", "date",
                    List.of("Column 'hash' is the datum hash for lookups",
                            "Column 'body' contains the CBOR-encoded datum")),
            entry("stake_registration",
                    "Stake address registration and deregistration certificates",
                    "DAILY", "date",
                    List.of()),
            entry("withdrawal",
                    "Reward withdrawals from stake addresses",
                    "DAILY", "date",
                    List.of("Column 'amount' is withdrawal in lovelace")),
            entry("adapot",
                    "Ada pot — treasury, reserves, fees, circulation, reward distribution per epoch",
                    "EPOCH", "epoch",
                    List.of("Partitioned by epoch",
                            "Key columns: treasury, reserves, circulation, fees, distributed_rewards",
                            "All amounts in lovelace")),
            entry("reward_rest",
                    "Treasury and reserves reward distributions (MIR-based)",
                    "EPOCH", "epoch",
                    List.of()),
            entry("unclaimed_reward_rest",
                    "Unclaimed treasury/reserves rewards",
                    "EPOCH", "epoch",
                    List.of()),
            entry("epoch_param",
                    "Protocol parameters per epoch",
                    "EPOCH", "epoch",
                    List.of("Column 'params' is a JSON string with all protocol parameters")),
            entry("stake_address_balance",
                    "Stake address balance snapshots",
                    "DAILY", "date",
                    List.of()),
            entry("cost_model",
                    "Plutus cost models for script execution pricing",
                    "DAILY", "date",
                    List.of()),
            entry("invalid_transaction",
                    "Transactions that failed phase-2 validation",
                    "DAILY", "date",
                    List.of()),
            entry("instant_reward",
                    "Instant rewards (MIR certificates)",
                    "EPOCH", "epoch",
                    List.of()),
            entry("mir",
                    "MIR (Move Instantaneous Rewards) certificates",
                    "EPOCH", "epoch",
                    List.of()),
            entry("gov_epoch_activity",
                    "Governance activity summary per epoch",
                    "EPOCH", "epoch",
                    List.of()),
            entry("rollback",
                    "Chain rollback events",
                    "DAILY", "date",
                    List.of()),
            entry("protocol_params_proposal",
                    "Protocol parameter change proposals (pre-Conway)",
                    "DAILY", "date",
                    List.of())
    );

    private static Map.Entry<String, TableMetadata> entry(String name, String desc, String partStrategy, String partCol, List<String> hints) {
        return Map.entry(name, new TableMetadata(name, desc, partStrategy, partCol, hints));
    }

    public static TableMetadata forTable(String tableName) {
        return METADATA.get(tableName);
    }

    /**
     * Get default metadata for a table not in the static map.
     */
    public static TableMetadata defaultFor(String tableName) {
        return new TableMetadata(tableName, "Analytics table", "UNKNOWN", null, List.of());
    }
}
