version: '3.9'

services:
  yaci-store-postgres:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=yaci
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=yaci_store
      - POSTGRES_LOGGING=true
    ports:
      - "54333:5432"
    volumes:
      - $PWD/db-data/yaci-store/:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U yaci -d yaci_store'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "100"
