networks:
  yaci-store-net:
    name: yaci-store-net

services:
  yaci-store-postgres:
    extends:
      file: postgres-compose.yml
      service: yaci-store-postgres
    networks:
      - yaci-store-net

  yaci-store-ledger-state:
    extends:
      file: yaci-store-ledger-state.yml
      service: yaci-store-ledger-state
    depends_on:
      yaci-store-postgres:
        condition: service_healthy
    networks:
      - yaci-store-net
