services:
  yaci-store:
    image: bloxbean/yaci-store:${tag}
    container_name: yaci-store
    env_file:
      - env
    ports:
      - ${YACI_STORE_PORT:-8080}:8080
    volumes:
      - $PWD/logs:/app/logs/
      - ./application.properties:/app/config/application.properties
      - ./application-ledger-state.properties:/app/config/application-ledger-state.properties
      - ./application-plugins.yml:/app/config/application-plugins.yml
      - ./plugin-scripts:/app/plugin-scripts/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "50"

