services:
  yaci-store-ledger-state:
    image: bloxbean/yaci-store-ledger-state:${tag}
    container_name: yaci-store-ledger-state
    environment:
      - SPRING_PROFILES_ACTIVE=ledger-state
    env_file:
      - env
    ports:
      - ${YAC_STORE_PORT:-8080}:8080
    volumes:
      - $PWD/logs:/app/logs/
      - ./application.properties:/app/config/application.properties
      - ./application-ledger-state.properties:/app/config/application-ledger-state.properties
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "50"

