spring:
  shell:
    interactive:
      enabled: true
#  config:
#    import: classpath:/git.properties
  banner:
    location: classpath:/banner.txt
  devtools:
    add-properties:logging: false

logging:
  level:
    org.springdoc: error
    org.springframework: error
    ch.qos.logback: error

shell.out.info: CYAN
shell.out.success: GREEN
shell.out.warning: YELLOW
shell.out.error: RED


spring.shell.history.enabled: true
spring.shell.history.name: admin-cli.history

# Rollback Configuration
# Custom rollback files (comma-separated list of YAML files)
# Examples: rollback.yml,classpath:custom-rollback.yml,file:///path/to/rollback.yml
# store.admin-cli.db.rollback.rollback-files: rollback.yml

# Manual rollback point configuration (required when block table is not available)
# These can be overridden via CLI options: --block, --block-hash, --slot --era
# store.admin-cli.db.rollback.point.block: 1255
# store.admin-cli.db.rollback.point.block-hash: block-hash
# store.admin-cli.db.rollback.point.slot: 1234567
# store.admin-cli.db.rollback.point.era: 2