spring:
  shell:
    interactive:
      enabled: true
#  config:
#    import: classpath:/git.properties
  banner:
    location: classpath:/banner.txt
  devtools:
    add-properties:logging: false

logging:
  level:
    org.springdoc: error
    org.springframework: error
    ch.qos.logback: error

shell.out.info: CYAN
shell.out.success: GREEN
shell.out.warning: YELLOW
shell.out.error: RED


spring.shell.history.enabled: true
spring.shell.history.name: admin-cli.history

# Rollback Configuration
# Custom rollback files (comma-separated list of YAML files)
# Examples: rollback.yml,classpath:custom-rollback.yml,file:///path/to/rollback.yml
store:
  dbutils:
    rollback_files: rollback.yml
  # Manual rollback point configuration (required when block table is not available)
  # These can be overridden via CLI options: --block, --block-hash, --slot
  rollback:
    point:
       block: 1000000
       block_hash: "abc123..."
       slot: 50000000