{
 "title": "Yaci Store Monitoring Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Sync Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "yaci_store_current_epoch" }
   ]
  },
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "yaci_store_current_block" }
   ]
  },
  {
   "title": "Current Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "yaci_store_current_block_time" }
   ]
  },
  {
   "title": "Current Era",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "yaci_store_current_era" }
   ]
  },
  {
   "title": "DB Current Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "yaci_store_current_db_epoch" }
   ]
  },
  {
   "title": "DB Current Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "yaci_store_current_db_block" }
   ]
  },
  {
   "title": "Protocol Magic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "yaci_store_protocol_magic" }
   ]
  },
  {
   "title": "Sync Mode (0=synching,1=synched)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "yaci_store_sync_mode" }
   ]
  },
  { "title": "Ada Pot Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "AdaPot Last Successful Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yaci_store_adapot_job_last_successful_epoch"
    }
   ]
  },
  {
   "title": "Treasury (Lovelace)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yaci_store_adapot_current_treasury",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Treasury (Ada)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yaci_store_adapot_current_treasury / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reserves (Lovelace)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yaci_store_adapot_current_reserves",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reserves (Ada)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yaci_store_adapot_current_reserves / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AdaPot Last Stake Snapshot Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yaci_store_adapot_job_last_successful_stake_snapshot_time"
    }
   ]
  },
  {
   "title": "AdaPot Last RewardCalc Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yaci_store_adapot_job_last_successful_rewardcalc_time"
    }
   ]
  },
  {
   "title": "AdaPot Last DRep Distr Snapshot Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yaci_store_adapot_job_last_successful_drep_distr_snapshot_time"
    }
   ]
  },
  {
   "title": "AdaPot Last Total Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yaci_store_adapot_job_last_successful_total_time"
    }
   ]
  },
  {
   "title": "AdaPot Last Update Reward Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yaci_store_adapot_job_last_successful_update_reward_time"
    }
   ]
  },
  {
   "title": "Last unsuccessful AdaPot Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yaci_store_adapot_job_last_unsuccessful_epoch",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AdaPot Calculation In-Progress Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yaci_store_adapot_job_inprogress_epoch",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}