
###
GET http://localhost:8080/api/v1/addresses/addr_test1qzx9hu8j4ah3auytk0mwcupd69hpc52t0cw39a65ndrah86djs784u92a3m5w475w3w35tyd6v3qumkze80j8a6h5tuqq5xe8y/utxos?page=0&count=100

###
POST http://localhost:8080/api/v1/utxos
Content-Type: application/json

[
  {
    "tx_hash": "297f6e4d0fe4483aeeb0e9017efdc8a3e65a4e7f5a562a52cae5254a552fff47",
    "output_index": 0
  },
  {
    "tx_hash": "297f6e4d0fe4483aeeb0e9017efdc8a3e65a4e7f5a562a52cae5254a552fff47",
    "output_index": 1
  },
  {
    "tx_hash": "93e43aa2e11dec72a28ac8c9692bdf91a6b5bd995106fcc90a3c45af57c7ea70",
    "output_index": 0
  }

]

###
GET http://localhost:8080/api/v1/utxos/a6fa627de15337fe4a6c935a2dcee7d3b990b8b8a0dc4ee6ef5e4595f25f6d9f/1

###
GET http://localhost:8080/api/v1/utxos?tx_hash=297f6e4d0fe4483aeeb0e9017efdc8a3e65a4e7f5a562a52cae5254a552fff47&output_index=0


###
GET http://localhost:8080/api/v1/txs/297f6e4d0fe4483aeeb0e9017efdc8a3e65a4e7f5a562a52cae5254a552fff47
###

GET http://localhost:8080/api/v1/scripts/9abe3db2c7b40203b62e24a8978dc8a4aa56b325a3686d20676d067b
###

GET http://localhost:8080/api/v1/epochs/parameters

###
GET http://localhost:8080/api/v1/txs

###
GET http://localhost:8080/api/v1/txs?page=0&count=10

###
GET http://localhost:8080/api/v1/txs/52dcb5409c1d49d5b3434e1efac13dfbb947e47711b68006e0ee28092f78fc8e/utxos

###
GET http://localhost:8080/api/v1/blocks/376120

###
GET http://localhost:8080/api/v1/blocks/pool/42946a3fe080dd99af599bfff10a05cd3de19bd38ed85b25dee35dd5?epoch=8


###
GET http://localhost:8080/api/v1/blocks

###
GET http://localhost:8080/api/v1/txs/936520b3011661ec2f8f1705f7ecc3e8bccb326f5a2311fd93a88d570ffc7917/scripts

###
GET http://localhost:8080/api/v1/txs/0d66c70aa9efa6bc1a635191abef9a0cd386a42b3f43c3199f3b794986995865/scripts

###
GET http://localhost:8080/api/v1/txs/a922efa2fcda9d64b33d88e83a3ce53943240955450dfca49cd033f9e38e4b80/scripts

###
GET http://localhost:8080/api/v1/txs/a5dbf6eacf522a1a065476bdf75dfe45db64d9d667f483220e208431b441a44d/metadata

###
GET http://localhost:8080/api/v1/txs/112ddf9a10147b83d613d8a1425af9d06375bbccd994fb35d94c245aa26be5f8/assets

###
GET http://localhost:8080/api/v1/txs/112ddf9a10147b83d613d8a1425af9d06375bbccd994fb35d94c245aa26be5f8/metadata

###
GET http://localhost:8080/api/v1/addresses/addr_test1wzcppsyg36f65jydjsd6fqu3xm7whxu6nmp3pftn9xfgd4ckah4da/utxos

###
GET http://localhost:8080/api/v1/txs/93e43aa2e11dec72a28ac8c9692bdf91a6b5bd995106fcc90a3c45af57c7ea70/utxos

###
GET http://localhost:8080/api/v1/blocks/404198/txs

###
GET http://localhost:8080/api/v1/blocks/546600341251701b439b701199847b0329f07f49da37edf7b83afb5150303cfb/txs

### pools ###
GET http://localhost:8080/api/v1/pools/registrations?page=0&count=10

###
GET http://localhost:8080/api/v1/pools/retirements?page=0&count=10

###
## Staking ##

GET http://localhost:8080/api/v1/stake/registrations
###

GET http://localhost:8080/api/v1/stake/deregistrations

###
GET http://localhost:8080/api/v1/stake/delegations
##
###
http://localhost:8080/api/v1/stake/registrations?page=0&count=20

###
#-- Test Data (Preprod)
#Contract tx
#Tx : 9f60322a6aa2841196cb56b573ba7abefe6d8cfe6cf6cdb2320e97a5b43e32ac for script
#RefInput: 11b8e9293d6fd63e4da589f7db03e20e7295db0472b047d8367959965b8ca204#0

###
http://localhost:8080/api/v1/accounts/stake_test1upfjudlteayz2ayenwkyqy77zxf92k69f28g0vur0rqmg3sjr95v7

### MIR
http://localhost:8080/api/v1/mir?page=0&count=10

### MIR by tx hash
http://localhost:8080/api/v1/txs/d61cf65f7f4dd40f48b30a02cdce13a089eb73e86ecc1a99eb6e7389045fa334/mir

### Utxo endpoints
### By address
http://localhost:8080/api/v1/addresses/addr_test1qqxnp3khzm7kcj9t23hskehat7428ghsenk0pfew4rqy5v9frnmht7uwrl073q4jvq20z82kh4rksyns540azhndqexqpvhgqr/utxos

### By ent address
http://localhost:8080/api/v1/addresses/addr_test1vqxnp3khzm7kcj9t23hskehat7428ghsenk0pfew4rqy5vq24rmml/utxos?page=0&count=100

### By stake address
http://localhost:8080/api/v1/addresses/stake_test1uz53eam4lw8plhlgs2exq983r4tt63mgzfc22h73teksvnq5hwnfs/utxos?page=0&count=100

### By address verification key
http://localhost:8080/api/v1/addresses/addr_vkh1p5cvd4ckl4ky3265du9kdl2l42369uxvanc2wt4gcp9rqzc60ky/utxos?page=0&count=1000


### By address and asset
http://localhost:8080/api/v1/addresses/addr_test1qrzqexq9rm5h5t7pqu7zvw2qlgqp80m0mwzttrkzzpt3nvafrnmht7uwrl073q4jvq20z82kh4rksyns540azhndqexqw6t2sa/utxos/749482b2fe4ac715bdeadc67db1f42600483ebb1913fa80a26411a63506c757475734d696e74546f6b656e2d32

### By ent address
http://localhost:8080/api/v1/addresses/addr_test1vqxnp3khzm7kcj9t23hskehat7428ghsenk0pfew4rqy5vq24rmml/utxos/4be3ff6f6ac1303b65adaa8c31b73395f488a6c3370b9694e6df21da4275726e546f6b656e54657374

### By stake address
http://localhost:8080/api/v1/addresses/stake_test1uz53eam4lw8plhlgs2exq983r4tt63mgzfc22h73teksvnq5hwnfs/utxos/749482b2fe4ac715bdeadc67db1f42600483ebb1913fa80a26411a63506c757475734d696e74546f6b656e2d32

### By address verification key
http://localhost:8080/api/v1/addresses/addr_vkh1p5cvd4ckl4ky3265du9kdl2l42369uxvanc2wt4gcp9rqzc60ky/utxos?page=0&count=1000

### Account balance by address
http://localhost:8080/api/v1/addresses/addr_test1vqxnp3khzm7kcj9t23hskehat7428ghsenk0pfew4rqy5vq24rmml/amounts

### Account balance by address
http://localhost:8080/api/v1/addresses/addr_test1qqxnp3khzm7kcj9t23hskehat7428ghsenk0pfew4rqy5v9frnmht7uwrl073q4jvq20z82kh4rksyns540azhndqexqpvhgqr/amounts

### Account balance by stake address
http://localhost:8080/api/v1/addresses/stake_test1uz53eam4lw8plhlgs2exq983r4tt63mgzfc22h73teksvnq5hwnfs/amounts

###
http://localhost:8080/api/v1/accounts/addr_test1vqxnp3khzm7kcj9t23hskehat7428ghsenk0pfew4rqy5vq24rmml/balance

###
http://localhost:8080/api/v1/accounts/stake_test1uz53eam4lw8plhlgs2exq983r4tt63mgzfc22h73teksvnq5hwnfs

###

#
GET http://localhost:8080/api/v1/metadata/txs/labels/721?page=3&count=99
accept: */*

###

# Assets tx by policy
GET http://localhost:8080/api/v1/assets/txs/policy/e2bab64ca481afc5a695b7db22fd0a7df4bf930158dfa652fb337999

###  Assets tx fingerprint
GET http://localhost:8080/api/v1/assets/txs/fingerprint/asset14p0rxzq3wc2a8tuftzkvjt5xt067rteaf8wqr3

### Assets tx by unit
GET http://localhost:8080/api/v1/assets/txs/unit/39086ef91d452d1b6ea9c8c92a2f3243467ddf93bf7c142d370e7d6443617264616e6f4275647a483253363434

### Unit
GET http://localhost:8080/api/v1/assets/txs/unit/e2bab64ca481afc5a695b7db22fd0a7df4bf930158dfa652fb33799953554d4d495441574152445344656669

### supply unit
GET http://localhost:8080/api/v1/assets/supply/unit/42f0e3706d2e0a0761db8da21387aadabe609a7cf328d249ebc2eeff96f0ab7cec670d934f369bfecab402f0387983733238b93be6213e61c94ea16f

### supply by policy
GET http://localhost:8080/api/v1/assets/supply/policy/39086ef91d452d1b6ea9c8c92a2f3243467ddf93bf7c142d370e7d64

### supply by fingerprint
GET http://localhost:8080/api/v1/assets/supply/fingerprint/asset14p0rxzq3wc2a8tuftzkvjt5xt067rteaf8wqr3

### Get redeemer by tx hash
GET http://localhost:8080/api/v1/txs/85dd9fe734810b311610b2c313e85cd1348d5c42bb3f35155322deb346ac40d4/redeemers

### Get datum by datum hash
GET http://localhost:8080/api/v1/scripts/datum/ee4a6a499024cae6b4d632c07fcad84dfdf0243381cd57fd8a15e6a42158a39f

### Get datum by hash
GET http://localhost:8080/api/v1/scripts/datum/ee4a6a499024cae6b4d632c07fcad84dfdf0243381cd57fd8a15e6a42158a39f/cbor

### Addresses by Asset
GET http://localhost:8080/api/v1/assets/f2dbd5db5ad0571ea533411e99dc960f582c0debbb731d746079f6a006b5e33ad456a338e7513cce2b112f33ae70024c0d3b77fabd006dac99cde45d/addresses?page=0&count=100&sort=desc

###
GET http://localhost:8080/api/v1/assets/627c22b8a13e0f7dad08ea3cc25ac6f254822acf9ded1b52b8578b41/addresses?page=0&count=100

### Epoch -- Epoch Param
GET http://localhost:8080/api/v1/epochs/latest/parameters

###
GET http://localhost:8080/api/v1/epochs/latest

###
GET http://localhost:8080/api/v1/epochs/2/parameters

### Param proposals
GET http://localhost:8080/api/v1/epoch/param-propsals?page=0&count=2&order=asc

### Get Witnesses
GET http://localhost:8080/api/v1/txs/64bc262000cdcf07927ee3b06a03b65f8fb81ca9c4b15cbbdd6a2689f974e9a3/witnesses

###
GET http://localhost:8080/api/v1/txs/ee0d811b75e0fbbd5d2bca9542b37225d2c5a58b8f371953d6494ab48ae3b9f0/witnesses

###
GET http://localhost:8080/api/v1/txs/8179c0867476f1d7a06c6abae22864ac280e2dc7083481f01ffd16382b7e3c59/witnesses

### Governance Data
# TODO: Replace all placeholder values with actual data  when governance data becomes available in preprod

### Get GovActionProposal list
GET http://localhost:8080/api/v1/gov-action-proposals?page=0&count=10

### Get GovActionProposal list by transaction hash
GET http://localhost:8080/api/v1/gov-action-proposals/{tx_hash}

### Get GovActionProposal list by governance action type
GET http://localhost:8080/api/v1/gov-action-proposals/gov-action-type/{gov_action_type}?page=0&count=10

### Get GovActionProposal list by return address
GET http://localhost:8080/api/v1/gov-action-proposals/return-address/{address}?page=0&count=10

### Get Voting Procedures list
GET http://localhost:8080/api/v1/voting-procedures?page=0&count=10

### Get Voting Procedures by GovActionProposal transaction hash
GET http://localhost:8080/api/v1/gov-action-proposals/{tx_hash}/voting-procedures?page=0&count=10

### Get Voting Procedures by GovActionProposal transaction hash and index in this transaction
GET http://localhost:8080/api/v1/gov-action-proposals/{tx_hash}/{index_in_transaction}/voting-procedures

### Get Voting Procedures by transaction hash
GET http://localhost:8080/api/v1/voting-procedures/{tx_hash}
