# Transaction Lifecycle Configuration
store:
  submit:
    lifecycle:
      # Enable transaction lifecycle tracking
      enabled: false
      
      # Block depth for SUCCESS state (configurable per application)
      success-block-depth: 15
      
      # Block depth for FINALIZED state (Cardano security parameter)
      finalized-block-depth: 2160
      
      # SUCCESS status check interval (milliseconds)
      success-check-interval-ms: 20000
      
      # FINALIZED status check interval (milliseconds)
      finalized-check-interval-ms: 3600000
      
      # WebSocket notifications (OPTIONAL)
      websocket:
        enabled: false
        endpoint: /ws/tx-lifecycle

