global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:

  - job_name: 'yaci-store'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['yaci-store:8080']
        labels:
          application: yaci-store
