networks:
  yaci-store-net:
    name: yaci-store-net

services:
  yaci-store-postgres:
    extends:
      file: postgres-compose.yml
      service: yaci-store-postgres
    restart: unless-stopped
    networks:
      - yaci-store-net

  yaci-store:
    extends:
      file: yaci-store.yml
      service: yaci-store
    depends_on:
      yaci-store-postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - yaci-store-net
