services:
  yaci-store:
    image: bloxbean/yaci-store:${tag}
    container_name: yaci-store-${INSTANCE_NAME:-default}
    env_file:
      - ../config/env
    ports:
      - "${YACI_STORE_PORT:-8080}:8080"
    volumes:
      - ../logs:/app/logs/
      - ../data:/app/data
      - ../config:/app/config
      - ../plugins/scripts:/app/plugins/scripts/
      - ../plugins/ext-jars:/app/plugins/ext-jars/
      - ../plugins/files:/app/plugins/files/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "50"

