name: Nightly Push to SNAPSHOT repo

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  commit-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build -PskipSigning=true --stacktrace
      - name: Publish package to SNAPSHOT repository
        run: ./gradlew publish -PskipSigning=true --warn --stacktrace
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
