name: Build and Release Yaci CLI Zip

on:
  push:
    tags:
      - 'rel-dev-*'

jobs:
  buildAndPush:
    strategy:
      matrix:
        os: ["ubuntu-20.04", "macos-14"]
    runs-on: ${{ matrix.os }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: '21.0.4'
          native-image-job-reports: 'true'
      - name: Get Tag from version file
        run: |
          VERSION=$(grep "tag=" config/gradle.properties | cut -d'=' -f2)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Copy CI specific native-image properties
        if: runner.os == 'Linux'
        run: |
            echo "os_prefix=linux" >> $GITHUB_ENV
      - name: MacOS specific env
        if: runner.os == 'macOS'
        run: |            
            echo "os_prefix=macos" >> $GITHUB_ENV        
      - name: Build with Gradle
        run: ./gradlew --no-daemon -i clean cliZip
      - name: Copy artifacts
        run: mv applications/all/build/output/yaci-store-${{ env.VERSION }}.zip applications/all/build/output/yaci-store-${{ env.VERSION }}-${{ env.os_prefix }}-${{ runner.arch }}.zip
      - uses: actions/upload-artifact@v4
        with:
          name: yaci-store-${{ env.VERSION }}-${{ env.os_prefix }}-${{ runner.arch }}
          path: ./applications/all/build/output/yaci-store-${{ env.VERSION }}-${{ env.os_prefix }}-${{ runner.arch }}.zip
