name: Upload Docker Compose ZIP

on:
  push:
    tags:
      - 'dv*'
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'liberica'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean dockerZip
      - name: 'Get Version Number'
        run: |
          ARTIFACT_VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')
          echo "VERSION=${ARTIFACT_VERSION}" >> $GITHUB_ENV
      - name: Upload Docker Compose ZIP to Release
        uses: softprops/action-gh-release@v1
        with:
          files: yaci-store-docker-${{ env.VERSION }}.zip
          tag_name: v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
